### ISSUE TITLE
[state]: infinite recursion

### ISSUE THREAD

**Issue by NVFedorov** [supermedium/superframe#280]
If something is listening to the state updates and modifies the state on state update this will fall into infinite recursion because the copying of the state to old state is happening after notifying subscribers.

Reproduce:
1. Have something listening to the state (i.e. some custom aframe component with ```keysToWatch=['anything']```)
2. This custom component will have a ```onStateUpdate()``` method. In this method dispatch any action in the state: ```this.el.sceneEl.emit('updateSomething', payload)```
3. Update ```state.anything``` and you will fall into infinite recursion.

The root cause: subscribers are being notified about state update before ```this.state``` is copied to ```this.lastState``` https://github.com/supermedium/superframe/blob/29c3859c666e4dd291a386459c2ca4f95b3b3a35/components/state/src/index.js#L116

https://github.com/supermedium/superframe/blob/29c3859c666e4dd291a386459c2ca4f95b3b3a35/components/state/src/index.js#L128

I have a fix ready, just want to confirm my understanding is correct before creating a pull request.

**Comment by ngokevin** [comment]
That seems plausible, I'd love to see a fix, thanks!

I've written this system in other languages, and evolved how it works a bit. I wait for a subscription change to fully release. If there are nested state changes, instead of immediately notifying subscribers, I pretty much batch them all towards at the end of the subscription loop to notify subscribers.

**Comment by NVFedorov** [comment]
It's very simple to be honest, but should work.
